### ISSUE TITLE
GitHub Actions workflows fails due to ruby version being unsupported by nokogiri

### ISSUE THREAD

**Issue by eUgEntOptIc44** [factbook/factbook#10]
Hi @geraldb,

New year, new issues. Looks like the `ruby` version needs to be upgraded to keep the workflow running.

The following errors has been reported in [yesterday's](https://github.com/factbook/factbook/actions/runs/3906410708/jobs/6674559265) run of the GitHub Actions workflow.

```
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
	The last version of nokogiri (>= 0) to support your Ruby & RubyGems was 1.13.10. Try installing it with `gem install nokogiri -v 1.13.10`
	nokogiri requires Ruby version >= 2.7, < 3.3.dev. The current ruby version is 2.6.10.210.
Successfully installed racc-1.6.2
Error: Process completed with exit code 1.
```

Hope you might have the time to look into that.

Cheers, Prost 🍻 

Jean-Luc

**Comment by geraldb** [comment]
Happy new year. Prosit 2023!   Thanks for checking.   I try to have a look later today - a quick first look at  the Gemfile <https://github.com/factbook/factbook/blob/master/2021/Gemfile> shows that there's no nokogiri version "hard-coded" or a lockfile for the gemfile checked in.    So as you write I try to upgrade the ruby version in <https://github.com/factbook/factbook/blob/master/.github/workflows/update.yml#L28> from 2.6 to 2.7. And retry. 

**Update**  The manual run was a success, thus, I close the ticket for now.

**Comment by eUgEntOptIc44** [comment]
Happy new year @geraldb 🥳 thanks for your help! I wish you the very best for 2023! 🍻
