### ISSUE TITLE
Automatic Update Failed  - New 2021 CIA World Factbook Website Redesign / Restructure

### ISSUE THREAD

**Issue by jgraves123** [factbook/factbook#5]
Hello,
You probably have noticed this, but I just wanted to highlight it if you haven't, that the automatic update for January 15th failed to build properly. Hopefully it's a quick fix :)

**Comment by geraldb** [comment]
Thanks for reporting. Unfortunately, it's not a quick fix.  The CIA World Factbook website design and structure changed in 2021 dramatically!  The good news is that the CIA now offers (unofficial?) json datasets. The bad news a lot of rework (and research) lies ahead for an update to the new format.   Cheers. Prosit 2021!

**Comment by jgraves123** [comment]
I’m sorry, that’s unfortunate. I did a quick search for cia factbook json files and didn’t see anything. Could you explain what your referencing?

**Comment by geraldb** [comment]
Sure. See the factbook discussion here <http://groups.google.com/group/openmundi> in the forum.  As an example try <https://www.cia.gov/the-world-factbook/geos/ag.json>

**Comment by geraldb** [comment]
FYI: I have updated the datasets with the new format "by hand". See <https://github.com/factbook/factbook.json>  if you find any mistakes or such in the new conversion, please tell. Cheers. Prost.
