### ISSUE TITLE
GitHub Actions workflow is inactive

### ISSUE THREAD

**Issue by eUgEntOptIc44** [factbook/factbook#6]
Hi @geraldb,
the GitHub Actions workflow of this repo is inactive:
![image](https://user-images.githubusercontent.com/90517741/144604671-69179c84-97f6-46d6-9452-6918bcabfa73.png)
I'd be very grateful if you could make a little commit to re-activate the workflow.

Hope your doing well.
Regards,
Jean-Luc

**Comment by geraldb** [comment]
Thanks for the reminder. The workflow is active again.
